name: test
permissions:
  contents: read
on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 3,6
jobs:
  test:
    name: "Run libc-test on zig master"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: mlugg/setup-zig@v1
      with:
        version: master
    - run: zig build test -Dtarget=x86_64-linux-musl --verbose --summary all
