name: test
permissions:
  contents: read
on:
  pull_request:
  push:
  schedule:
    - cron: 0 0 * * 3,6
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        optimize:
          - Debug
          - ReleaseFast
        target:
          - triple: aarch64-linux-musl
            image: ubuntu-24.04-arm
            qemu: false
          - triple: aarch64_be-linux-musl
            image: ubuntu-latest
            qemu: true
          - triple: hexagon-linux-musl
            image: ubuntu-latest
            qemu: true
          - triple: loongarch64-linux-musl
            image: ubuntu-latest
            qemu: true
          - triple: powerpc64-linux-musl
            image: ubuntu-latest
            qemu: true
          - triple: powerpc64le-linux-musl
            image: ubuntu-latest
            qemu: true
          - triple: riscv32-linux-musl
            image: ubuntu-latest
            qemu: true
          - triple: riscv64-linux-musl
            image: ubuntu-latest
            qemu: true
          - triple: s390x-linux-musl
            image: ubuntu-latest
            qemu: true
          - triple: x86-linux-musl
            image: ubuntu-latest
            qemu: false
          - triple: x86_64-linux-musl
            image: ubuntu-latest
            qemu: false
          - triple: x86_64-linux-muslx32
            image: ubuntu-latest
            qemu: false
          - triple: aarch64-windows-gnu
            image: windows-11-arm
            qemu: false
          - triple: x86-windows-gnu
            image: windows-latest
            qemu: false
          - triple: x86_64-windows-gnu
            image: windows-latest
            qemu: false
    name: "Run libc-test ${{ matrix.optimize }} on ${{ matrix.target.triple }}"
    runs-on: ${{ matrix.target.image }}
    steps:
    - uses: mlugg/setup-zig@v2
      with:
        version: master
    - uses: actions/checkout@v3
    - name: Install QEMU
      if: ${{ matrix.target.qemu }}
      run: sudo apt-get install --yes qemu-user
    - name: Build all test cases
      run: zig build -Dtarget=${{ matrix.target.triple }} -Doptimize=${{ matrix.optimize }} -Dskip-foreign-checks --verbose --summary all -Dunstable install
    - name: Run test cases
      run: zig build -Dtarget=${{ matrix.target.triple }} -Doptimize=${{ matrix.optimize }} -Dskip-foreign-checks --verbose --summary all -fqemu test
